name: Publish to CurseForge and GitHub
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release'
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish to CurseForge and GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          version: ${{ inputs.version }}
          version-type: release
          name: "[${{ inputs.version }}] OmniEconomy"
          changelog-file: CHANGELOG.md
          loaders: neoforge
          game-versions: 1.21.1
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
          java: 21
#          curseforge-id: 1371365
#          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}